name: eecs6322-project
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch=2.2.0
  - opencv
  - colour
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - numpy=1.26.3
  - matplotlib=3.8.0
  - notebook=7.0.6
  - pillow=10.2.0
  - pip:
      - pudb==2024.1
